class RandomGenerator {
	constructor(min, max) {
		this.min = min;
		this.max = max;
		if (isNaN(this.min)) {
			this.min = 1;
		}
		if (isNaN(this.max)) {
			this.max = 10;
		}
		this.storage = null;
		//takes in the minimum and maximum values
		//if they are not defined, it sets the minimum to 1, and the max to 10
		//makes storage for the random number
	}
	generate() {
		this.storage = Math.floor(Math.random() * (this.max - this.min + 1)) + this.min;
		//make a random value between the minimum and maximum values
		//and store the number into the storage from the constructor
	}
	getRange() {
		var range = {
			min: this.min,
			max: this.max
		};
		return range;
		//return an object with min and max, min being the minimum value for the generator, max being the maximum value
		//returns a basic object literal
	}
	getNum() {
		return this.storage;
		//return the random number that was generated by generate()
	}
}

var test = new RandomGenerator(0, 100);